data_postgres:
  build: .
  dockerfile: Dockerfile.data

data_mongo:
  image: mongo
  command: /bin/true
  volumes:
    - /data/mongo

mongo:
  image: mongo
  volumes_from:
    - data_mongo

postgres:
  image: postgres
  environment:
    PGDATA: /data/postgres
  volumes_from:
    - data_postgres

redis:
  image: redis

web:
  build: .
  dockerfile: Dockerfile.web
  expose:
    - "8000:8000"
  links:
    - postgres
    - contacts

worker:
  build: .
  dockerfile: Dockerfile.web
  links:
    - redis
    - postgres
  command: /bin/sh /celery.sh

contacts:
  image: cuevee/contacts
  links:
    - mongo

nginx:
  build: .
  dockerfile: Dockerfile.nginx
  ports:
    - "80:80"
  links:
    - web
    - contacts
