data:
  build: .
  dockerfile: Dockerfile.data
postgres:
  image: postgres
  environment:
    PGDATA: /dbdata
  volumes_from:
    - data
web:
  build: .
  dockerfile: Dockerfile.dev
  ports:
    - "80:80"
  links:
    - postgres
